### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by Teicu** [dradis/burp-dradis#3]
Hello 

any help to solve this issue please? 

I get the follwoing error during the installation ( I'm using Burp P v 2.0.20 and Macbook ) Thanks

> java.lang.RuntimeException: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `anchor=' for #<Java::JavaAwt::GridBagConstraints:0x6ebe21e6>
	at burp.fhv.a(Unknown Source)
	at burp.cnz.addSuiteTab(Unknown Source)
	at burp.fc9.addSuiteTab(Unknown Source)
	at burp.env.addSuiteTab(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:455)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:316)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:46)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:339)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:317)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:171)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:158)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:339)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:317)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:108)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:95)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:34)
	at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	at org.jruby.Ruby.runInterpreter(Ruby.java:891)
	at org.jruby.Ruby.runInterpreter(Ruby.java:895)
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:118)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:90)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:142)
	at burp.csk.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
org.jruby.embed.EvalFailedException: java.lang.RuntimeException: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `anchor=' for #<Java::JavaAwt::GridBagConstraints:0x6ebe21e6>
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:137)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:90)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:142)
	at burp.csk.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `anchor=' for #<Java::JavaAwt::GridBagConstraints:0x6ebe21e6>
	at burp.fhv.a(burp/fhv)
	at burp.cnz.addSuiteTab(burp/cnz)
	at burp.fc9.addSuiteTab(burp/fc9)
	at burp.env.addSuiteTab(burp/env)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:455)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:316)
	at RUBY.registerExtenderCallbacks(/Users/mariusavram/.BurpSuite/bapps/c1be8787ebdd45f58c091f6ae30f1af2/burp-dradis.rb:89)
	at RUBY.<main>(<script>:1)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:891)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:895)
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(org/jruby/embed/internal/EmbedEvalUnitImpl.java:118)
	at org.jruby.embed.jsr223.JRubyEngine.eval(org/jruby/embed/jsr223/JRubyEngine.java:90)
	at org.jruby.embed.jsr223.JRubyEngine.eval(org/jruby/embed/jsr223/JRubyEngine.java:142)
	at burp.csk.lambda$registerExtenderCallbacks$0(burp/csk)
	at java.util.concurrent.Executors$RunnableAdapter.call(java/util/concurrent/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java/util/concurrent/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java/lang/Thread.java:834)

**Comment by rachkor** [comment]
@Teicu thanks for reaching out! Here's the guide for installing and configuring the Burp-Dradis extension: https://dradisframework.com/support/guides/customization/configure_burp-dradis.html. When do you run into this error? And, how do you have the extension configured? Finally, are you using Dradis CE or Pro? We'll get this figured out!

**Comment by clive7391** [comment]
I had the same issue with the Installed version of Burp-Pro on Win and Linux and Dradis Pro. I used the Burp-Pro jar file and it worked.
